"""
Fixtures for OWASP ZAP integration testing.

Provides sample ZAP scan results and alert data for unit tests.
"""
from datetime import datetime
from typing import Any, Dict, List

import pytest


# =============================================================================
# Sample ZAP API Responses
# =============================================================================


def get_sample_zap_version_response() -> Dict[str, str]:
    """Get a sample ZAP version API response."""
    return {"version": "2.14.0"}


def get_sample_zap_spider_status(progress: int = 100) -> Dict[str, str]:
    """Get a sample ZAP spider status response."""
    return {"status": str(progress)}


def get_sample_zap_ascan_status(progress: int = 100) -> Dict[str, str]:
    """Get a sample ZAP active scan status response."""
    return {"status": str(progress)}


def get_sample_zap_alerts(num_alerts: int = 3) -> List[Dict[str, Any]]:
    """
    Get sample ZAP alert data.

    Args:
        num_alerts: Number of alerts to generate

    Returns:
        List of alert dictionaries
    """
    alerts = []

    alert_templates = [
        {
            "alert": "SQL Injection",
            "risk": "High",
            "confidence": "Medium",
            "description": "SQL injection may be possible.",
            "solution": "Use prepared statements or parameterized queries.",
            "reference": "https://owasp.org/www-community/attacks/SQL_Injection",
            "cweid": "89",
            "wascid": "19",
            "pluginid": "40018",
        },
        {
            "alert": "Cross Site Scripting (XSS)",
            "risk": "High",
            "confidence": "Medium",
            "description": "Cross-site Scripting (XSS) is possible.",
            "solution": "Encode all output and validate input.",
            "reference": "https://owasp.org/www-community/attacks/xss/",
            "cweid": "79",
            "wascid": "8",
            "pluginid": "40012",
        },
        {
            "alert": "Missing Anti-CSRF Tokens",
            "risk": "Medium",
            "confidence": "Medium",
            "description": "No Anti-CSRF tokens were found in a HTML submission form.",
            "solution": "Implement anti-CSRF tokens.",
            "reference": "https://owasp.org/www-community/attacks/csrf",
            "cweid": "352",
            "wascid": "9",
            "pluginid": "10202",
        },
        {
            "alert": "X-Content-Type-Options Header Missing",
            "risk": "Low",
            "confidence": "Medium",
            "description": "The Anti-MIME-Sniffing header is not set.",
            "solution": "Set X-Content-Type-Options: nosniff",
            "reference": "https://owasp.org/www-project-secure-headers/",
            "cweid": "693",
            "wascid": "15",
            "pluginid": "10021",
        },
        {
            "alert": "Information Disclosure - Suspicious Comments",
            "risk": "Informational",
            "confidence": "Low",
            "description": "The response appears to contain suspicious comments.",
            "solution": "Remove comments from production code.",
            "reference": "",
            "cweid": "200",
            "wascid": "13",
            "pluginid": "10027",
        },
    ]

    for i in range(min(num_alerts, len(alert_templates))):
        template = alert_templates[i]
        alerts.append({
            **template,
            "url": f"http://test-service.default.svc.cluster.local:8080/api/endpoint{i}",
            "param": f"param{i}",
            "attack": "test' OR '1'='1",
            "evidence": f"SQL error message {i}",
            "alertRef": f"{template['pluginid']}-{i}",
            "sourceid": "1",
            "messageId": f"{100 + i}",
        })

    return alerts


def get_sample_zap_alerts_response(num_alerts: int = 3) -> Dict[str, List]:
    """Get a sample ZAP alerts API response."""
    return {"alerts": get_sample_zap_alerts(num_alerts)}


# =============================================================================
# Passive Security Check Results
# =============================================================================


def get_sample_passive_security_findings() -> Dict[str, Any]:
    """
    Get sample passive security check findings.

    These are generated by the ZAPService without active scanning.
    """
    return {
        "findings": [
            {
                "alert": "Missing X-Frame-Options Header",
                "risk": "Medium",
                "confidence": "High",
                "description": "X-Frame-Options header is not included in the HTTP response.",
                "solution": "Add X-Frame-Options: DENY or SAMEORIGIN header",
                "cweid": "1021",
                "wascid": "15",
            },
            {
                "alert": "Missing Content-Security-Policy Header",
                "risk": "Medium",
                "confidence": "High",
                "description": "Content-Security-Policy header is not set.",
                "solution": "Implement a Content Security Policy",
                "cweid": "693",
                "wascid": "15",
            },
            {
                "alert": "HTTP Protocol Used",
                "risk": "Medium",
                "confidence": "High",
                "description": "The application uses unencrypted HTTP protocol.",
                "solution": "Use HTTPS instead of HTTP",
                "cweid": "319",
                "wascid": "4",
            },
            {
                "alert": "Server Information Disclosure",
                "risk": "Low",
                "confidence": "High",
                "description": "Server header discloses server version information.",
                "solution": "Remove or obscure server version information",
                "cweid": "200",
                "wascid": "13",
            },
        ],
        "total": 4,
        "by_risk": {
            "high": 0,
            "medium": 3,
            "low": 1,
            "informational": 0,
        },
    }


# =============================================================================
# Security Findings (Combined Format)
# =============================================================================


def get_sample_security_findings(
    zap_alerts: int = 2,
    pentest_findings: int = 1,
) -> Dict[str, Any]:
    """
    Get sample security findings in the combined format.

    This represents the merged results from ZAP and pentesting scans.
    """
    timestamp = datetime.utcnow().isoformat()

    zap_alerts_data = get_sample_zap_alerts(zap_alerts)
    totals = {
        "high_risk": sum(1 for a in zap_alerts_data if a["risk"] == "High"),
        "medium_risk": sum(1 for a in zap_alerts_data if a["risk"] == "Medium"),
        "low_risk": sum(1 for a in zap_alerts_data if a["risk"] == "Low"),
        "informational": sum(1 for a in zap_alerts_data if a["risk"] == "Informational"),
    }

    return {
        "zap_scan": {
            "scan_type": "active",
            "status": "completed",
            "target_urls": ["http://test-service.default.svc.cluster.local:8080"],
            "alerts": zap_alerts_data,
            "scan_timestamp": timestamp,
        },
        "pentest_scan": {
            "scan_type": "automated",
            "status": "completed",
            "target": "test-service.default.svc.cluster.local",
            "findings": [
                {
                    "tool": "nmap",
                    "finding": "Open port 8080/tcp - nginx",
                    "severity": "informational",
                }
                for _ in range(pentest_findings)
            ],
            "scan_timestamp": timestamp,
        },
        "totals": totals,
    }


# =============================================================================
# Pytest Fixtures
# =============================================================================


@pytest.fixture
def zap_version_response():
    """Fixture providing ZAP version response."""
    return get_sample_zap_version_response()


@pytest.fixture
def zap_spider_status():
    """Fixture providing ZAP spider status response."""
    return get_sample_zap_spider_status()


@pytest.fixture
def zap_ascan_status():
    """Fixture providing ZAP active scan status response."""
    return get_sample_zap_ascan_status()


@pytest.fixture
def zap_alerts():
    """Fixture providing sample ZAP alerts."""
    return get_sample_zap_alerts()


@pytest.fixture
def zap_alerts_response():
    """Fixture providing ZAP alerts API response."""
    return get_sample_zap_alerts_response()


@pytest.fixture
def passive_security_findings():
    """Fixture providing passive security check findings."""
    return get_sample_passive_security_findings()


@pytest.fixture
def combined_security_findings():
    """Fixture providing combined security findings (ZAP + pentest)."""
    return get_sample_security_findings()


# =============================================================================
# Mock HTTP Response Helpers
# =============================================================================


def create_zap_http_response(status_code: int, json_data: Dict) -> Any:
    """
    Create a mock HTTP response for ZAP API calls.

    Args:
        status_code: HTTP status code
        json_data: JSON response data

    Returns:
        Mock response object
    """
    from unittest.mock import Mock

    response = Mock()
    response.status_code = status_code
    response.ok = 200 <= status_code < 300
    response.json.return_value = json_data
    response.text = str(json_data)
    return response


@pytest.fixture
def mock_zap_responses(mocker):
    """
    Fixture providing mocked HTTP responses for ZAP API.

    Returns a dict of URL patterns to responses.
    """
    import re

    responses = {
        # Version check
        re.compile(r".*/JSON/core/view/version/"): create_zap_http_response(
            200, get_sample_zap_version_response()
        ),
        # Spider status
        re.compile(r".*/JSON/spider/view/status/"): create_zap_http_response(
            200, get_sample_zap_spider_status()
        ),
        # Active scan status
        re.compile(r".*/JSON/ascan/view/status/"): create_zap_http_response(
            200, get_sample_zap_ascan_status()
        ),
        # Alerts
        re.compile(r".*/JSON/core/view/alerts/"): create_zap_http_response(
            200, get_sample_zap_alerts_response()
        ),
        # New session
        re.compile(r".*/JSON/core/action/newSession/"): create_zap_http_response(
            200, {"Result": "OK"}
        ),
        # Access URL
        re.compile(r".*/JSON/core/action/accessUrl/"): create_zap_http_response(
            200, {"Result": "OK"}
        ),
        # Start spider
        re.compile(r".*/JSON/spider/action/scan/"): create_zap_http_response(
            200, {"scan": "1"}
        ),
        # Start active scan
        re.compile(r".*/JSON/ascan/action/scan/"): create_zap_http_response(
            200, {"scan": "1"}
        ),
    }

    return responses
